---
title: "Veterinary Perfusion Analysis"
author: "Antje Hartmann, Volkher Scholz, Ines Lautenschlaeger"
date: "06/07/2019"
output: html_document
---

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(data.table)
library(lme4)
# devtools::use_rstudio(".")
# library(roxygen2)
# install("veterinary-perfusion-analysis")
```

# Extract Perfusion parameters

## Data Import

```{r}
data = fread('../data/all_animals.csv', stringsAsFactors = TRUE)
head(data, 10)
```

## Compute parameters

```{r}
perfdata = vetperf.data(data, arrival_frame = 9, delta_t = 1.6, echo_time = 0.03, baseroi = "cs", iterations = 10)
perfdata = na.omit(perfdata)
```

# Analyze disease influence

## Format data

```{r}
perfdata[animal %in% c(1:8), state := "healty"]
perfdata[animal %in% c(9:20), state := "diseased"]
perfdata$state = as.factor(perfdata$state)
```

## Plot densities

```{r}
ggplot(perfdata) + aes(x = MTT, color = state) + geom_density() + facet_wrap(~roi)
ggplot(perfdata) + aes(x = CBF, color = state) + geom_density() + xlim(0,5.) + facet_wrap(~roi)
ggplot(perfdata) + aes(x = CBV, color = state) + geom_density() + xlim(0,5.) + facet_wrap(~roi)
```

## Check for significance

```{r}
model.mtt.0 = lmer(MTT ~ roi + (1|animal), data=perfdata)
model.mtt.1 = lmer(MTT ~ roi*state + (1|animal), data=perfdata)
anova(model.mtt.0, model.mtt.1)
```


```{r}
model.cbf.0 = glmer(CBF ~ roi + (1|animal), data=perfdata, family = Gamma(link = "log"))
model.cbf.1 = glmer(CBF ~ roi*state + (1|animal), data=perfdata, family = Gamma(link = "log"))
anova(model.cbf.0, model.cbf.1)
```

# Conclusion





